FROM amd64/python:3.10-slim

WORKDIR /app

# Install system dependencies required for building mysqlclient
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies without using requirements.txt
RUN pip install Flask Flask-RESTful Flask-SQLAlchemy Flask-Cors flask-socketio flask-jwt-extended Flask-Bcrypt mysqlclient

COPY . .

EXPOSE 5001

CMD python server.py